useful: buildTest test valgrind_check linter_check
buildMain: main.c
	gcc -o main main.c 

buildTest: tests.c
	gcc -o tests -Dmain=_main main.c tests.c 

test:
	./tests
	
valgrind_check:
	echo "20\n2.2032" > input.txt
	valgrind ./tests < input.txt
	
linter_check:
	cpp main.c

.PHONY: clean
clean:
	rm -rf lab1/